{{ config(materialized='view') }}

-- GOLD LAYER RULE: this model may only ref() silver models (never bronze or
-- raw directly). See CLAUDE.md section 4.4.
--
-- Daily %RUNNING vs %STOPPED/MAINTENANCE/ERROR per machine, computed by
-- overlapping each silver_dim_machines SCD2 interval against a calendar-day
-- spine. The spine is generated by the adapter-dispatched day_spine() macro,
-- which emits native sequence()+explode() on Databricks.

with scd2 as (

    select
        machine_id,
        machine_type,
        status_value,
        valid_from,
        coalesce(valid_to, {{ dbt.current_timestamp() }}) as valid_to
    from {{ ref('silver_dim_machines') }}

),

spine_bounds as (

    select
        min(cast(valid_from as date)) as first_day,
        max(cast(valid_to as date))   as last_day
    from scd2

),

day_spine as (

    {{ day_spine('b.first_day', 'b.last_day', 'spine_bounds b') }}

),

machines as (

    select distinct machine_id, machine_type from scd2

),

machine_days as (

    select
        m.machine_id,
        m.machine_type,
        ds.day
    from machines m
    cross join day_spine ds

),

overlap as (

    select
        md.machine_id,
        md.machine_type,
        md.day,
        s.status_value,
        greatest(
            0,
            {{ dbt.datediff(
                'greatest(s.valid_from, cast(md.day as timestamp))',
                'least(s.valid_to, cast(md.day as timestamp) + interval 1 day)',
                'second'
            ) }}
        ) as overlap_seconds
    from machine_days md
    inner join scd2 s
        on s.machine_id = md.machine_id
       and s.valid_from < cast(md.day as timestamp) + interval 1 day
       and s.valid_to   > cast(md.day as timestamp)

),

daily_totals as (

    select
        machine_id,
        machine_type,
        day,
        sum(overlap_seconds) as total_seconds,
        sum(case when status_value = 'RUNNING' then overlap_seconds else 0 end)                    as running_seconds,
        sum(case when status_value in ('STOPPED', 'MAINTENANCE', 'ERROR') then overlap_seconds else 0 end) as down_seconds,
        sum(case when status_value = 'IDLE' then overlap_seconds else 0 end)                        as idle_seconds
    from overlap
    group by machine_id, machine_type, day

)

select
    machine_id,
    machine_type,
    day as event_date,
    total_seconds,
    running_seconds,
    down_seconds,
    idle_seconds,
    round(100.0 * running_seconds / nullif(total_seconds, 0), 2) as pct_running,
    round(100.0 * down_seconds / nullif(total_seconds, 0), 2)    as pct_down,
    round(100.0 * idle_seconds / nullif(total_seconds, 0), 2)    as pct_idle
from daily_totals
